additionalPrometheusRulesMap:
  prometheus-notification-queue-running-full:
    groups:
    - name: prometheus-notification-queue-running-full
      rules:
      - alert: prometheus-notification-queue-running-full-warning
        expr: (predict_linear(prometheus_notifications_queue_length[5m], 60 * 30) >  min_over_time(prometheus_notifications_queue_capacity[5m]))
        for: 15m
        labels:
          severity: warning
          group_name: prometheus-notification-queue-running-full
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alert notification queue of Prometheus {{$labels.namespace}}/{{$labels.pod}} is running full.
            This warning alert fires after 15m.
          runbook_url: default_runbook_url
          summary: Prometheus alert notification queue predicted to run full in less than 30m.
          dashboard_url: default_dashboard_url
      - alert: prometheus-notification-queue-running-full-critical
        expr: (predict_linear(prometheus_notifications_queue_length[5m], 60 * 30) >  min_over_time(prometheus_notifications_queue_capacity[5m]))
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-notification-queue-running-full
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alert notification queue of Prometheus {{$labels.namespace}}/{{$labels.pod}} is running full.
            This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: Prometheus alert notification queue predicted to run full in less than 30m.
          dashboard_url: default_dashboard_url
