additionalPrometheusRulesMap:
  prometheustargetlimithit:
    groups:
    - name: prometheustargetlimithit
      rules:
      - alert: prometheustargetlimithit-warning
        expr: increase(prometheus_target_scrape_pool_exceeded_target_limit_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m]) > 0
        for: 15m
        labels:
          severity: warning
          group_name: prometheustargetlimithit
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has dropped {{ printf "%.0f" $value }} targets because the number of targets exceeded the configured target_limit.
          runbook_url: default_runbook_url
          summary: Prometheus has dropped targets because some scrape configs have exceeded the targets limit.
          dashboard_url: default_dashboard_url
      - alert: prometheustargetlimithit-critical
        expr: increase(prometheus_target_scrape_pool_exceeded_target_limit_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m]) > 0
        for: 30m
        labels:
          severity: critical
          group_name: prometheustargetlimithit
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has dropped {{ printf "%.0f" $value }} targets because the number of targets exceeded the configured target_limit.
          runbook_url: default_runbook_url
          summary: Prometheus has dropped targets because some scrape configs have exceeded the targets limit.
          dashboard_url: default_dashboard_url
