additionalPrometheusRulesMap:
  prometheus-errors-sending-alerts-to-some-alertmanagers:
    groups:
    - name: prometheus-errors-sending-alerts-to-some-alertmanagers
      rules:
      - alert: prometheus-errors-sending-alerts-to-some-alertmanagers-warning
        expr: (rate(prometheus_notifications_errors_total[5m]) /  rate(prometheus_notifications_sent_total[5m])) * 100 > 1
        for: 15m
        labels:
          severity: warning
          group_name: prometheus-errors-sending-alerts-to-some-alertmanagers
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ printf "%.1f" $value }}% of alerts sent by Prometheus {{$labels.namespace}}/{{$labels.pod}}
            to Alertmanager {{$labels.alertmanager}} were affected by errors. This warning alert fires after
            15m.
          runbook_url: default_runbook_url
          summary: More than 1% of alerts sent by Prometheus to a specific Alertmanager were affected by errors.
          dashboard_url: default_dashboard_url
      - alert: prometheus-errors-sending-alerts-to-some-alertmanagers-critical
        expr: (rate(prometheus_notifications_errors_total[5m]) /  rate(prometheus_notifications_sent_total[5m])) * 100 > 1
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-errors-sending-alerts-to-some-alertmanagers
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ printf "%.1f" $value }}% of alerts sent by Prometheus {{$labels.namespace}}/{{$labels.pod}}
            to Alertmanager {{$labels.alertmanager}} were affected by errors. This critical alert fires
            after 30m.
          runbook_url: default_runbook_url
          summary: More than 1% of alerts sent by Prometheus to a specific Alertmanager were affected by errors.
          dashboard_url: default_dashboard_url
