additionalPrometheusRulesMap:
  prometheus-not-connected-to-alertmanagers:
    groups:
    - name: prometheus-not-connected-to-alertmanagers
      rules:
      - alert: prometheus-not-connected-to-alertmanagers-warning
        expr: max_over_time(prometheus_notifications_alertmanagers_discovered[5m]) < 1
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-not-connected-to-alertmanagers
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is not connected to any Alertmanagers. This
            warning alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is not connected to any Alertmanagers.
          dashboard_url: default_dashboard_url
      - alert: prometheus-not-connected-to-alertmanagers-critical
        expr: max_over_time(prometheus_notifications_alertmanagers_discovered[5m]) < 1
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-not-connected-to-alertmanagers
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is not connected to any Alertmanagers. This
            critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is not connected to any Alertmanagers.
          dashboard_url: default_dashboard_url
