additionalPrometheusRulesMap:
  prometheus-missing-rule-evaluations:
    groups:
    - name: prometheus-missing-rule-evaluations
      rules:
      - alert: prometheus-missing-rule-evaluations-warning
        expr: increase(prometheus_rule_group_iterations_missed_total[5m]) > 0
        for: 15m
        labels:
          severity: warning
          group_name: prometheus-missing-rule-evaluations
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has missed {{ printf "%.0f" $value }} rule
            group evaluations in the last 5m. This warning alert fires after 15m.
          runbook_url: default_runbook_url
          summary: Prometheus is missing rule evaluations due to slow rule group evaluation.
          dashboard_url: default_dashboard_url
      - alert: prometheus-missing-rule-evaluations-critical
        expr: increase(prometheus_rule_group_iterations_missed_total[5m]) > 0
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-missing-rule-evaluations
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has missed {{ printf "%.0f" $value }} rule
            group evaluations in the last 5m. This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: Prometheus is missing rule evaluations due to slow rule group evaluation.
          dashboard_url: default_dashboard_url
