additionalPrometheusRulesMap:
  prometheus-tsdb-reloads-failing:
    groups:
    - name: prometheus-tsdb-reloads-failing
      rules:
      - alert: prometheus-tsdb-reloads-failing-warning
        expr: increase(prometheus_tsdb_reloads_failures_total[3h]) > 0
        for: 4h
        labels:
          severity: warning
          group_name: prometheus-tsdb-reloads-failing
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has detected {{$value | humanize}} reload
            failures over the last 3h. This warning alert fires after 4h.
          runbook_url: default_runbook_url
          summary: Prometheus has issues reloading blocks from disk.
          dashboard_url: default_dashboard_url
      - alert: prometheus-tsdb-reloads-failing-critical
        expr: increase(prometheus_tsdb_reloads_failures_total[3h]) > 0
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-tsdb-reloads-failing
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has detected {{$value | humanize}} reload
            failures over the last 3h. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus has issues reloading blocks from disk.
          dashboard_url: default_dashboard_url
