additionalPrometheusRulesMap:
  prometheus-remote-write-desired-shards:
    groups:
    - name: prometheus-remote-write-desired-shards
      rules:
      - alert: prometheus-remote-write-desired-shards-warning
        expr: (max_over_time(prometheus_remote_storage_shards_desired[5m]) >  max_over_time(prometheus_remote_storage_shards_max[5m]))
        for: 15m
        labels:
          severity: warning
          group_name: prometheus-remote-write-desired-shards
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} remote write desired shards calculation wants
            to run {{ $value }} shards for queue {{ $labels.remote_name}}:{{ $labels.url }}, which is more
            than the max of {{ printf
            `prometheus_remote_storage_shards_max{instance="%s",job="kube-prometheus-stack-prometheus",namespace="prometheus"}`
            $labels.instance | query | first | value }}. This warning alert fires after 15m.
          runbook_url: default_runbook_url
          summary: Prometheus remote write desired shards calculation wants to run more than configured max shards.
          dashboard_url: default_dashboard_url
      - alert: prometheus-remote-write-desired-shards-critical
        expr: (max_over_time(prometheus_remote_storage_shards_desired[5m]) >  max_over_time(prometheus_remote_storage_shards_max[5m]))
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-remote-write-desired-shards
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} remote write desired shards calculation wants
            to run {{ $value }} shards for queue {{ $labels.remote_name}}:{{ $labels.url }}, which is more
            than the max of {{ printf
            `prometheus_remote_storage_shards_max{instance="%s",job="kube-prometheus-stack-prometheus",namespace="prometheus"}`
            $labels.instance | query | first | value }}. This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: Prometheus remote write desired shards calculation wants to run more than configured max shards.
          dashboard_url: default_dashboard_url
