additionalPrometheusRulesMap:
  prometheus-duplicate-timestamps:
    groups:
    - name: prometheus-duplicate-timestamps
      rules:
      - alert: prometheus-duplicate-timestamps-warning
        expr: rate(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-duplicate-timestamps
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }}
            samples/s with different values but duplicated timestamp. This warning alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is dropping samples with duplicate timestamps.
          dashboard_url: default_dashboard_url
      - alert: prometheus-duplicate-timestamps-critical
        expr: rate(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-duplicate-timestamps
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }}
            samples/s with different values but duplicated timestamp. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is dropping samples with duplicate timestamps.
          dashboard_url: default_dashboard_url
