additionalPrometheusRulesMap:
  prometheus-not-ingesting-samples:
    groups:
    - name: prometheus-not-ingesting-samples
      rules:
      - alert: prometheus-not-ingesting-samples-warning
        expr: (sum without(type) (rate(prometheus_tsdb_head_samples_appended_total[5m])) <= 0 and  (sum without(scrape_job) (prometheus_target_metadata_cache_entries) > 0  or    sum without(rule_group) (prometheus_rule_group_rules) > 0))
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-not-ingesting-samples
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting samples. This warning alert
            fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is not ingesting samples.
          dashboard_url: default_dashboard_url
      - alert: prometheus-not-ingesting-samples-critical
        expr: (sum without(type) (rate(prometheus_tsdb_head_samples_appended_total[5m])) <= 0 and  (sum without(scrape_job) (prometheus_target_metadata_cache_entries) > 0  or    sum without(rule_group) (prometheus_rule_group_rules) > 0))
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-not-ingesting-samples
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting samples. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus is not ingesting samples.
          dashboard_url: default_dashboard_url
