additionalPrometheusRulesMap:
  prometheus-out-of-order-timestamps:
    groups:
    - name: prometheus-out-of-order-timestamps
      rules:
      - alert: prometheus-out-of-order-timestamps-warning
        expr: rate(prometheus_target_scrapes_sample_out_of_order_total[5m]) > 0
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-out-of-order-timestamps
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }}
            samples/s with timestamps arriving out of order. This warning alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus drops samples with out-of-order timestamps.
          dashboard_url: default_dashboard_url
      - alert: prometheus-out-of-order-timestamps-critical
        expr: rate(prometheus_target_scrapes_sample_out_of_order_total[5m]) > 0
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-out-of-order-timestamps
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }}
            samples/s with timestamps arriving out of order. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Prometheus drops samples with out-of-order timestamps.
          dashboard_url: default_dashboard_url
