additionalPrometheusRulesMap:
  prometheus-sd-refresh-failure:
    groups:
    - name: prometheus-sd-refresh-failure
      rules:
      - alert: prometheus-sd-refresh-failure-warning
        expr: increase(prometheus_sd_refresh_failures_total[10m]) > 0
        for: 20m
        labels:
          severity: warning
          group_name: prometheus-sd-refresh-failure
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to refresh SD with mechanism
            {{$labels.mechanism}}. This warning alert fires after 20m.
          runbook_url: default_runbook_url
          summary: Failed Prometheus SD refresh.
          dashboard_url: default_dashboard_url
      - alert: prometheus-sd-refresh-failure-critical
        expr: increase(prometheus_sd_refresh_failures_total[10m]) > 0
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-sd-refresh-failure
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to refresh SD with mechanism
            {{$labels.mechanism}}. This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: Failed Prometheus SD refresh.
          dashboard_url: default_dashboard_url
