additionalPrometheusRulesMap:
  prometheuskuberneteslistwatchfailures:
    groups:
    - name: prometheuskuberneteslistwatchfailures
      rules:
      - alert: prometheuskuberneteslistwatchfailures-warning
        expr: increase(prometheus_sd_kubernetes_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m]) > 0
        for: 15m
        labels:
          severity: warning
          group_name: prometheuskuberneteslistwatchfailures
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Kubernetes service discovery of Prometheus {{$labels.namespace}}/{{$labels.pod}} is experiencing {{ printf "%.0f" $value }} failures with LIST/WATCH requests to the Kubernetes API in the last 5 minutes.
          runbook_url: default_runbook_url
          summary: Requests in Kubernetes SD are failing.
          dashboard_url: default_dashboard_url
      - alert: prometheuskuberneteslistwatchfailures-critical
        expr: increase(prometheus_sd_kubernetes_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m]) > 0
        for: 30m
        labels:
          severity: critical
          group_name: prometheuskuberneteslistwatchfailures
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Kubernetes service discovery of Prometheus {{$labels.namespace}}/{{$labels.pod}} is experiencing {{ printf "%.0f" $value }} failures with LIST/WATCH requests to the Kubernetes API in the last 5 minutes.
          runbook_url: default_runbook_url
          summary: Requests in Kubernetes SD are failing.
          dashboard_url: default_dashboard_url
