additionalPrometheusRulesMap:
  clusternode-cpuratio:
    groups:
      - name: kube-prometheus-node-recording-rules
        rules:
          - expr: cluster:node_cpu:sum_rate5m / count(sum(node_cpu_seconds_total) by (instance, cpu))
            record: cluster:node_cpu:ratio
