additionalPrometheusRulesMap:
  instancenode-network-transmit-bytesratesum:
    groups:
      - name: kube-prometheus-node-recording-rules
        rules:
          - expr: sum(rate(node_network_transmit_bytes_total[3m])) by (instance)
            record: instance:node_network_transmit_bytes:rate:sum
