additionalPrometheusRulesMap:
  instancenode-cpuratesum:
    groups:
      - name: kube-prometheus-node-recording-rules
        rules:
          - expr: sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal"}[3m])) by (instance)
            record: instance:node_cpu:rate:sum
