---
alertmanager:
  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      # Default inhibit rules
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'group_name'
          - 'node_hostname'
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'group_name'
          - 'namespace'
          - 'pod'
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'group_name'
          - 'cluster'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'

      # When a host is down, suppress all other alerts for the same Kubernetes node in the same cluster
      - source_matchers:
          - group_name="node-host-down"
        target_matchers:
          - group_name!="node-host-down"
          - k8s_node_name!=""
        equal:
          - cluster
          - k8s_node_name

      # When a Kubernetes node is NotReady, suppress all other alerts from that same node
      - source_matchers:
          - group_name="kube-node-not-ready"
        target_matchers:
          - group_name!="kube-node-not-ready"
          - k8s_node_name!=""
        equal:
          - cluster
          - k8s_node_name
    route:
      group_by: ['namespace', 'alertname', 'host_name']
      group_wait: 30s
      group_interval: 4h
      repeat_interval: 12h
      routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
        - receiver: 'all_alerts_receiver'
          continue: true
          matchers:
            - severity =~ "warning|critical"
        - receiver: 'alert_proxy_receiver'
          continue: true
          matchers:
            - severity =~ "critical"
        - receiver: 'msteams_config'
    receivers:
      - name: 'null'
      - name: 'all_alerts_receiver' # pixelview
        webhook_configs:
          - url: 'https://flex.ohthree.com/webhook/prometheus?servicekey=369fb1a9-6961-4d16-a7a1-fc7d03d1cffc'
            send_resolved: true
      - name: 'alert_proxy_receiver'
        webhook_configs:
          - url: 'http://alert-proxy.rackspace.svc.cluster.local/alert/process'
            send_resolved: false
      - name: 'msteams_config'
        msteams_configs:
        - send_resolved: true
          webhook_url: 'https://prod-87.westus.logic.azure.com:443/workflows/ab8510b4b01f4062b6dcaea3068ce4fc/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=-56Trh1232a_zMwNaen0lhEE2auy1R9h3xDbrqnPX-g'
