defaultRules:
  additionalRuleLabels:
    rackspace_com_coreAccountID: '5002029'
    rackspace_com_overseerID: '935811'
alertmanager:
  alertmanagerSpec:
    externalUrl: "https://alertmanager.dev.dfw.ohthree.com"
  logLevel: info
prometheus:
  prometheusSpec:
    externalUrl: "https://prometheus.dev.dfw.ohthree.com"
    scrapeConfigSelector:
      matchLabels:
        prometheus: system-monitoring-prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 150Gi
