additionalPrometheusRulesMap:
  target-down:
    groups:
    - name: target-down
      rules:
      - alert: target-down-warning
        expr: ((100 * count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector.*"} == 0) / count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector"})) >  25) and on (cluster, job, namespace)count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector"}) >= 4
        for: 5m
        labels:
          severity: warning
          group_name: target-down
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
          correlation_key: target/{{ $labels.cluster }}/{{ $labels.namespace }}/{{ $labels.job }}
          correlation_scope: target
        annotations:
          description: '{{ printf "%.1f" $value }}% of {{ $labels.job }} targets in namespace {{ $labels.namespace }} are down.'
          runbook_url: default_runbook_url
          summary: One or more targets are unreachable.
          dashboard_url: default_dashboard_url
      - alert: target-down-critical
        expr: ((100 * count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector.*"} == 0) / count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector"})) >  25) and on (cluster, job, namespace)count by (cluster, job, namespace) (up{job!~"opentelemetry-kube-stack-.*-collector"}) >= 4
        for: 10m
        labels:
          severity: critical
          group_name: target-down
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
          correlation_key: target/{{ $labels.cluster }}/{{ $labels.namespace }}/{{ $labels.job }}
          correlation_scope: target
        annotations:
          description: '{{ printf "%.1f" $value }}% of {{ $labels.job }} targets in namespace {{ $labels.namespace }} are down.'
          runbook_url: default_runbook_url
          summary: One or more targets are unreachable.
          dashboard_url: default_dashboard_url
