additionalPrometheusRulesMap:
  prometheus-operator-watch-errors:
    groups:
    - name: prometheus-operator-watch-errors
      rules:
      - alert: prometheus-operator-watch-errors-warning
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_failed_total[5m])) / sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_total[5m]))) > 0.4
        for: 15m
        labels:
          severity: warning
          group_name: prometheus-operator-watch-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Errors while performing watch operations in controller {{$labels.controller}} in
            {{$labels.namespace}} namespace. This warning alert fires after 15m.
          runbook_url: default_runbook_url
          summary: Errors while performing watch operations in controller.
          dashboard_url: default_dashboard_url
      - alert: prometheus-operator-watch-errors-critical
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_failed_total[5m])) / sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_total[5m]))) > 0.4
        for: 30m
        labels:
          severity: critical
          group_name: prometheus-operator-watch-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Errors while performing watch operations in controller {{$labels.controller}} in
            {{$labels.namespace}} namespace. This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: Errors while performing watch operations in controller.
          dashboard_url: default_dashboard_url
