additionalPrometheusRulesMap:
  prometheus-operator-status-update-errors:
    groups:
    - name: prometheus-operator-status-update-errors
      rules:
      - alert: prometheus-operator-status-update-errors-warning
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_errors_total[5m]))) / (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_operations_total[5m]))) > 0.1
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-operator-status-update-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of status update operations failed for {{ $labels.controller
            }} controller in {{ $labels.namespace }} namespace. This warning alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while updating objects status.
          dashboard_url: default_dashboard_url
      - alert: prometheus-operator-status-update-errors-critical
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_errors_total[5m]))) / (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_operations_total[5m]))) > 0.1
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-operator-status-update-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of status update operations failed for {{ $labels.controller
            }} controller in {{ $labels.namespace }} namespace. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while updating objects status.
          dashboard_url: default_dashboard_url
