additionalPrometheusRulesMap:
  prometheus-operator-reconcile-errors:
    groups:
    - name: prometheus-operator-reconcile-errors
      rules:
      - alert: prometheus-operator-reconcile-errors-warning
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_reconcile_errors_total[5m]))) / (sum by (cluster,controller,namespace) (rate(prometheus_operator_reconcile_operations_total[5m]))) > 0.1
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-operator-reconcile-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of reconciling operations failed for {{ $labels.controller }}
            controller in {{ $labels.namespace }} namespace. This warning alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while reconciling objects.
          dashboard_url: default_dashboard_url
      - alert: prometheus-operator-reconcile-errors-critical
        expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_reconcile_errors_total[5m]))) / (sum by (cluster,controller,namespace) (rate(prometheus_operator_reconcile_operations_total[5m]))) > 0.1
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-operator-reconcile-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of reconciling operations failed for {{ $labels.controller }}
            controller in {{ $labels.namespace }} namespace. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while reconciling objects.
          dashboard_url: default_dashboard_url
