additionalPrometheusRulesMap:
  prometheus-operator-node-lookup-errors:
    groups:
    - name: prometheus-operator-node-lookup-errors
      rules:
      - alert: prometheus-operator-node-lookup-errors-warning
        expr: rate(prometheus_operator_node_address_lookup_errors_total[5m]) > 0.1
        for: 10m
        labels:
          severity: warning
          group_name: prometheus-operator-node-lookup-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace. This warning alert
            fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while reconciling Prometheus.
          dashboard_url: default_dashboard_url
      - alert: prometheus-operator-node-lookup-errors-critical
        expr: rate(prometheus_operator_node_address_lookup_errors_total[5m]) > 0.1
        for: 10m
        labels:
          severity: critical
          group_name: prometheus-operator-node-lookup-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Errors while reconciling Prometheus.
          dashboard_url: default_dashboard_url
