additionalPrometheusRulesMap:
  cluster-verb-scopeapiserver-request-sli-duration-seconds-countincrease30d:
    groups:
      - name: kube-apiserver-availability-rules
        rules:
          - expr: sum by (cluster, verb, scope) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le="+Inf"})
            record: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d
