additionalPrometheusRulesMap:
  codeapiserver-request-totalincrease30d:
    groups:
      - name: kube-apiserver-availability-rules
        rules:
          - expr: sum by (cluster, code) (code_verb:apiserver_request_total:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
            labels:
              verb: write
            record: code:apiserver_request_total:increase30d
