groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerClusterDown
    annotations:
      description: '{{ $value | humanizePercentage }} of Alertmanager instances within
        the {{$labels.job}} cluster have been up for less than half of the last 5m.'
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerclusterdown
      summary: Half or more of the Alertmanager instances within the same cluster
        are down.
    expr: "(\n  count by (namespace,service,cluster) (\n    avg_over_time(up{job=\"\
      kube-prometheus-stack-alertmanager\",container=\"alertmanager\",namespace=\"\
      prometheus\"}[5m]) < 0.5\n  )\n/\n  count by (namespace,service,cluster) (\n\
      \    up{job=\"kube-prometheus-stack-alertmanager\",container=\"alertmanager\"\
      ,namespace=\"prometheus\"}\n  )\n)\n>= 0.5"
    for: 5m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: critical
