groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerClusterCrashlooping
    annotations:
      description: '{{ $value | humanizePercentage }} of Alertmanager instances within
        the {{$labels.job}} cluster have restarted at least 5 times in the last 10m.'
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerclustercrashlooping
      summary: Half or more of the Alertmanager instances within the same cluster
        are crashlooping.
    expr: "(\n  count by (namespace,service,cluster) (\n    changes(process_start_time_seconds{job=\"\
      kube-prometheus-stack-alertmanager\",container=\"alertmanager\",namespace=\"\
      prometheus\"}[10m]) > 4\n  )\n/\n  count by (namespace,service,cluster) (\n\
      \    up{job=\"kube-prometheus-stack-alertmanager\",container=\"alertmanager\"\
      ,namespace=\"prometheus\"}\n  )\n)\n>= 0.5"
    for: 5m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: critical
