groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerFailedToSendAlerts
    annotations:
      description: Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} failed to
        send {{ $value | humanizePercentage }} of notifications to {{ $labels.integration
        }}.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedtosendalerts
      summary: An Alertmanager instance failed to send notifications.
    expr: "(\n  rate(alertmanager_notifications_failed_total{job=\"kube-prometheus-stack-alertmanager\"\
      ,container=\"alertmanager\",namespace=\"prometheus\"}[15m])\n/\n  ignoring (reason)\
      \ group_left rate(alertmanager_notifications_total{job=\"kube-prometheus-stack-alertmanager\"\
      ,container=\"alertmanager\",namespace=\"prometheus\"}[15m])\n)\n> 0.01"
    for: 5m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
