groups:
- name: prometheus-operator
  rules:
  - alert: PrometheusOperatorWatchErrors
    annotations:
      description: Errors while performing watch operations in controller {{$labels.controller}}
        in {{$labels.namespace}} namespace.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/prometheusoperatorwatcherrors
      summary: Errors while performing watch operations in controller.
    expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_failed_total{job="kube-prometheus-stack-operator",namespace="prometheus"}[5m]))
      / sum by (cluster,controller,namespace) (rate(prometheus_operator_watch_operations_total{job="kube-prometheus-stack-operator",namespace="prometheus"}[5m])))
      > 0.4
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
