additionalPrometheusRulesMap:
  am-failed-reload:
    groups:
    - name: am-failed-reload
      rules:
      - alert: alertmanager-failed-reload-warning
        expr: max_over_time(alertmanager_config_last_reload_successful{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) == 0
        for: 10m
        labels:
          severity: warning
          group_name: alertmanager-failed-reload
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Configuration has failed to load for {{ $labels.namespace }}/{{ $labels.pod}}. This warning
            alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Reloading an Alertmanager configuration has failed.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-failed-reload-critical
        expr: max_over_time(alertmanager_config_last_reload_successful{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) == 0
        for: 10m
        labels:
          severity: critical
          group_name: alertmanager-failed-reload
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Configuration has failed to load for {{ $labels.namespace }}/{{ $labels.pod}}. This critical
            alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Reloading an Alertmanager configuration has failed.
          dashboard_url: default_dashboard_url
