additionalPrometheusRulesMap:
  am-members-inconsistent:
    groups:
    - name: am-members-inconsistent
      rules:
      - alert: alertmanager-members-inconsistent-warning
        expr: max_over_time(alertmanager_cluster_members{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) < on (namespace,service,cluster) group_left  count by (namespace,service,cluster) (max_over_time(alertmanager_cluster_members{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]))
        for: 15m
        labels:
          severity: warning
          group_name: alertmanager-members-inconsistent
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} has only found {{ $value }} members of the
            {{$labels.job}} cluster. This warning alert fires after 15m.
          runbook_url: default_runbook_url
          summary: A member of an Alertmanager cluster has not found all other cluster members.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-members-inconsistent-critical
        expr: max_over_time(alertmanager_cluster_members{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) < on (namespace,service,cluster) group_left  count by (namespace,service,cluster) (max_over_time(alertmanager_cluster_members{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]))
        for: 30m
        labels:
          severity: critical
          group_name: alertmanager-members-inconsistent
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} has only found {{ $value }} members of the
            {{$labels.job}} cluster. This critical alert fires after 30m.
          runbook_url: default_runbook_url
          summary: A member of an Alertmanager cluster has not found all other cluster members.
          dashboard_url: default_dashboard_url
