additionalPrometheusRulesMap:
  am-cluster-crash-looping:
    groups:
    - name: am-cluster-crash-looping
      rules:
      - alert: alertmanager-cluster-crash-looping-warning
        expr: (count by (namespace,service,cluster) (changes(process_start_time_seconds{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}[10m]) > 4  ) / count by (namespace,service,cluster) (up{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}  ))>= 0.5
        for: 5m
        labels:
          severity: warning
          group_name: alertmanager-cluster-crash-looping
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of Alertmanager instances within the {{$labels.job}} cluster
            have restarted at least 5 times in the last 10m. This warning alert fires after 5m.
          runbook_url: default_runbook_url
          summary: Half or more of the Alertmanager instances within the same cluster are crashlooping.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-cluster-crash-looping-critical
        expr: (count by (namespace,service,cluster) (changes(process_start_time_seconds{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}[10m]) > 4 ) / count by (namespace,service,cluster) (up{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}  ))>= 0.5
        for: 10m
        labels:
          severity: critical
          group_name: alertmanager-cluster-crash-looping
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of Alertmanager instances within the {{$labels.job}} cluster
            have restarted at least 5 times in the last 10m. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Half or more of the Alertmanager instances within the same cluster are crashlooping.
          dashboard_url: default_dashboard_url
