additionalPrometheusRulesMap:
  am-failed-to-send-alerts:
    groups:
    - name: am-failed-to-send-alerts
      rules:
      - alert: alertmanager-failed-to-send-alerts-warning
        expr: (rate(alertmanager_notifications_failed_total{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[15m]) /  ignoring (reason) group_left rate(alertmanager_notifications_total{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}[15m])) > 0.01
        for: 5m
        labels:
          severity: warning
          group_name: alertmanager-failed-to-send-alerts
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} failed to send {{ $value |
            humanizePercentage }} of notifications to {{ $labels.integration }}. This warning alert fires
            after 5m.
          runbook_url: default_runbook_url
          summary: An Alertmanager instance failed to send notifications.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-failed-to-send-alerts-critical
        expr: (rate(alertmanager_notifications_failed_total{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[15m]) /  ignoring (reason) group_left rate(alertmanager_notifications_total{job="kube-prometheus-stack-alertmanager",container="alertmanager",namespace="prometheus"}[15m])) > 0.01
        for: 10m
        labels:
          severity: critical
          group_name: alertmanager-failed-to-send-alerts
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} failed to send {{ $value |
            humanizePercentage }} of notifications to {{ $labels.integration }}. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: An Alertmanager instance failed to send notifications.
          dashboard_url: default_dashboard_url
