additionalPrometheusRulesMap:
  am-cluster-failed-to-send-alerts:
    groups:
    - name: am-cluster-failed-to-send-alerts
      rules:
      - alert: alertmanager-cluster-failed-to-send-alerts-warning
        expr: min by (namespace,service, integration) (rate(alertmanager_notifications_failed_total{job="kube-prometheus-stack-alertmanager",container="alertmanager", integration!~`.*`}[15m]) /  ignoring (reason) group_left rate(alertmanager_notifications_total{job="kube-prometheus-stack-alertmanager",container="alertmanager", integration!~`.*`}[15m])) > 0.01
        for: 5m
        labels:
          severity: warning
          group_name: alertmanager-cluster-failed-to-send-alerts
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            The minimum notification failure rate to {{ $labels.integration }} sent from any instance in the
            {{$labels.job}} cluster is {{ $value | humanizePercentage }}. This warning alert fires after 5m.
          runbook_url: default_runbook_url
          summary: All Alertmanager instances in a cluster failed to send notifications to a non-critical integration.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-cluster-failed-to-send-alerts-critical
        expr: min by (namespace,service, integration) (rate(alertmanager_notifications_failed_total{job="kube-prometheus-stack-alertmanager",container="alertmanager", integration!~`.*`}[15m]) /  ignoring (reason) group_left rate(alertmanager_notifications_total{job="kube-prometheus-stack-alertmanager",container="alertmanager", integration!~`.*`}[15m])) > 0.01
        for: 10m
        labels:
          severity: critical
          group_name: alertmanager-cluster-failed-to-send-alerts
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            The minimum notification failure rate to {{ $labels.integration }} sent from any instance in the
            {{$labels.job}} cluster is {{ $value | humanizePercentage }}. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: All Alertmanager instances in a cluster failed to send notifications to a non-critical integration.
          dashboard_url: default_dashboard_url
