additionalPrometheusRulesMap:
  am-cluster-down:
    groups:
    - name: am-cluster-down
      rules:
      - alert: alertmanager-cluster-down-warning
        expr: (count by (namespace,service,cluster) ( avg_over_time(up{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) < 0.5 ) /  count by (namespace,service,cluster) ( up{job="kube-prometheus-stack-alertmanager",container="alertmanager"} )) >= 0.5
        for: 5m
        labels:
          severity: warning
          group_name: alertmanager-cluster-down
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of Alertmanager instances within the {{$labels.job}} cluster
            have been up for less than half of the last 5m. This warning alert fires after 5m.
          runbook_url: default_runbook_url
          summary: Half or more of the Alertmanager instances within the same cluster are down.
          dashboard_url: default_dashboard_url
      - alert: alertmanager-cluster-down-critical
        expr: (count by (namespace,service,cluster) ( avg_over_time(up{job="kube-prometheus-stack-alertmanager",container="alertmanager"}[5m]) < 0.5 ) /  count by (namespace,service,cluster) ( up{job="kube-prometheus-stack-alertmanager",container="alertmanager"} )) >= 0.5
        for: 10m
        labels:
          severity: critical
          group_name: alertmanager-cluster-down
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: >-
            {{ $value | humanizePercentage }} of Alertmanager instances within the {{$labels.job}} cluster
            have been up for less than half of the last 5m. This critical alert fires after 10m.
          runbook_url: default_runbook_url
          summary: Half or more of the Alertmanager instances within the same cluster are down.
          dashboard_url: default_dashboard_url
