additionalPrometheusRulesMap:
  kube-pod-crash-looping:
    groups:
      - name: kube-pod-crash-looping
        rules:
          - alert: kube-pod-crash-looping-warning
            expr: >-
              max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace=~".*"}[5m]) >= 1
            for: 5m
            labels:
              severity: warning
              group_name: kube-pod-crash-looping
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Pod {{ $labels.exported_namespace }}/{{ $labels.exported_pod }} ({{ $labels.container }}) is in waiting state
                (reason: "CrashLoopBackOff"). This warning alert fires after
                5m.
              runbook_url: default_runbook_url
              summary: Pod is crash looping.
              dashboard_url: default_dashboard_url
          - alert: kube-pod-crash-looping-critical
            expr: >-
              max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace=~".*"}[5m]) >= 1
            for: 10m
            labels:
              severity: critical
              group_name: kube-pod-crash-looping
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Pod {{ $labels.exported_namespace }}/{{ $labels.exported_pod }} ({{ $labels.container }}) is in waiting state
                (reason: "CrashLoopBackOff"). This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Pod is crash looping.
              dashboard_url: default_dashboard_url
