additionalPrometheusRulesMap:
  kubelet-server-certificate-expiration:
    groups:
      - name: kubelet-server-certificate-expiration
        rules:
          - alert: kubelet-server-certificate-expiration-warning
            expr: kubelet_certificate_manager_server_ttl_seconds < 86400
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-server-certificate-expiration
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Server certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }} on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet server certificate is about to expire.
              dashboard_url: default_dashboard_url
          - alert: kubelet-server-certificate-expiration-critical
            expr: kubelet_certificate_manager_server_ttl_seconds < 86400
            for: 15m
            labels:
              severity: critical
              group_name: kubelet-server-certificate-expiration
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Server certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }} on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet server certificate is about to expire.
              dashboard_url: default_dashboard_url
