additionalPrometheusRulesMap:
  kube-node-readiness-flapping:
    groups:
      - name: kube-node-readiness-flapping
        rules:
          - alert: kube-node-readiness-flapping-warning
            expr: >-
              sum(changes(kube_node_status_condition{status="true",condition="Ready"}[15m])) by (node) > 2

              and on (node) kube_node_spec_unschedulable == 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-readiness-flapping
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                The readiness status of node {{ $labels.node }} has changed {{ $value }} times in the last 15
                minutes. This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Node readiness status is flapping.
              dashboard_url: default_dashboard_url
          - alert: kube-node-readiness-flapping-critical
            expr: >-
              sum(changes(kube_node_status_condition{status="true",condition="Ready"}[15m])) by (node) > 2

              and on (node) kube_node_spec_unschedulable == 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-node-readiness-flapping
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                The readiness status of node {{ $labels.node }} has changed {{ $value }} times in the last 15
                minutes. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Node readiness status is flapping.
              dashboard_url: default_dashboard_url
