additionalPrometheusRulesMap:
  kube-deployment-replicas-mismatch:
    groups:
      - name: kube-deployment-replicas-mismatch
        rules:
          - alert: kube-deployment-replicas-mismatch-warning
            expr: >-
              ( kube_deployment_spec_replicas{namespace=~".*"} > kube_deployment_status_replicas_available{namespace=~".*"} )

              and ( changes(kube_deployment_status_replicas_available{namespace=~".*"}[10m]) == 0 )
            for: 5m
            labels:
              severity: warning
              group_name: kube-deployment-replicas-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: deployment/{{ $labels.namespace }}/{{ $labels.deployment }}
              correlation_scope: deployment
            annotations:
              description: >-
                Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number
                of replicas for longer than 5 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Deployment has not matched the expected number of replicas.
              dashboard_url: default_dashboard_url
          - alert: kube-deployment-replicas-mismatch-critical
            expr: >-
              ( kube_deployment_spec_replicas{namespace=~".*"} > kube_deployment_status_replicas_available{namespace=~".*"} )

              and ( changes(kube_deployment_status_replicas_available{namespace=~".*"}[10m]) == 0 )
            for: 10m
            labels:
              severity: critical
              group_name: kube-deployment-replicas-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: deployment/{{ $labels.namespace }}/{{ $labels.deployment }}
              correlation_scope: deployment
            annotations:
              description: >-
                Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number
                of replicas for longer than 10 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Deployment has not matched the expected number of replicas.
              dashboard_url: default_dashboard_url
