additionalPrometheusRulesMap:
  kube-quota-fully-used:
    groups:
      - name: kube-quota-fully-used
        rules:
          - alert: kube-quota-fully-used-warning
            expr: >-
              k8s.resource_quota.used{job="otelcol-k8scluster"} / ignoring(instance, job) (k8s.resource_quota.hard_limit{job="otelcol-k8scluster"} > 0) == 1
            for: 5m
            labels:
              severity: warning
              group_name: kube-quota-fully-used
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Namespace quota is fully used.
              dashboard_url: default_dashboard_url
          - alert: kube-quota-fully-used-critical
            expr: >-
              k8s.resource_quota.used{job="otelcol-k8scluster"} / ignoring(instance, job) (k8s.resource_quota.hard_limit{job="otelcol-k8scluster"} > 0) == 1
            for: 15m
            labels:
              severity: critical
              group_name: kube-quota-fully-used
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Namespace quota is fully used.
              dashboard_url: default_dashboard_url
