additionalPrometheusRulesMap:
  kube-pdb-not-enough-healthy-pods:
    groups:
      - name: kube-pdb-not-enough-healthy-pods
        rules:
          - alert: kube-pdb-not-enough-healthy-pods-warning
            expr: >-
              ( kube_poddisruptionbudget_status_desired_healthy{namespace=~".*"} - kube_poddisruptionbudget_status_current_healthy{namespace=~".*"} ) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-pdb-not-enough-healthy-pods
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: pdb/{{ $labels.namespace }}/{{ $labels.poddisruptionbudget }}
              correlation_scope: pdb
            annotations:
              description: >-
                PDB {{ $labels.namespace }}/{{ $labels.poddisruptionbudget }} expects {{
                $value }} more healthy pods. The desired number of healthy pods has not been met for at least 5
                minutes.
              runbook_url: default_runbook_url
              summary: PDB does not have enough healthy pods.
              dashboard_url: default_dashboard_url
          - alert: kube-pdb-not-enough-healthy-pods-critical
            expr: >-
              ( kube_poddisruptionbudget_status_desired_healthy{namespace=~".*"} - kube_poddisruptionbudget_status_current_healthy{namespace=~".*"} ) > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-pdb-not-enough-healthy-pods
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: pdb/{{ $labels.namespace }}/{{ $labels.poddisruptionbudget }}
              correlation_scope: pdb
            annotations:
              description: >-
                PDB {{ $labels.namespace }}/{{ $labels.poddisruptionbudget }} expects {{
                $value }} more healthy pods. The desired number of healthy pods has not been met for at least 10
                minutes.
              runbook_url: default_runbook_url
              summary: PDB does not have enough healthy pods.
              dashboard_url: default_dashboard_url
