additionalPrometheusRulesMap:
  kubelet-too-many-pods:
    groups:
      - name: kubelet-too-many-pods
        rules:
          - alert: kubelet-too-many-pods-warning
            expr: >-
              ( max by (instance) ( kubelet_running_pods{job="kubelet", metrics_path="/metrics"} > 1 ) *

              on (instance) group_left(node) max by (instance, node) ( kubelet_node_name{job="kubelet", metrics_path="/metrics"} ) ) /

              on (node) group_left() max by (node) ( kube_node_status_capacity{resource="pods"} != 1 ) > 0.95
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-too-many-pods
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Kubelet '{{ $labels.node }}' is running at {{ $value | humanizePercentage }} of its Pod capacity.
                This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Kubelet is running at capacity.
              dashboard_url: default_dashboard_url
          - alert: kubelet-too-many-pods-critical
            expr: >-
              ( max by (instance) ( kubelet_running_pods{job="kubelet", metrics_path="/metrics"} > 1 ) *

              on (instance) group_left(node) max by (instance, node) ( kubelet_node_name{job="kubelet", metrics_path="/metrics"} ) ) /

              on (node) group_left() max by (node) ( kube_node_status_capacity{resource="pods"} != 1 ) > 0.95
            for: 10m
            labels:
              severity: critical
              group_name: kubelet-too-many-pods
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Kubelet '{{ $labels.node }}' is running at {{ $value | humanizePercentage }} of its Pod capacity.
                This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Kubelet is running at capacity.
              dashboard_url: default_dashboard_url
