additionalPrometheusRulesMap:
  kube-aggregated-api-down:
    groups:
      - name: kube-aggregated-api-down
        rules:
          - alert: kube-aggregated-api-down-warning
            expr: >-
              (1 - max by (name, namespace, cluster)(avg_over_time(aggregator_unavailable_apiservice{job="apiserver"}[10m]))) * 100 < 85
            for: 5m
            labels:
              severity: warning
              group_name: kube-aggregated-api-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes aggregated API {{ $labels.name }}/{{ $labels.namespace }} has been only {{ $value | humanize }}% available over the last 10m on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes aggregated API is down.
              dashboard_url: default_dashboard_url
          - alert: kube-aggregated-api-down-critical
            expr: >-
              (1 - max by (name, namespace, cluster)(avg_over_time(aggregator_unavailable_apiservice{job="apiserver"}[10m]))) * 100 < 85
            for: 15m
            labels:
              severity: critical
              group_name: kube-aggregated-api-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes aggregated API {{ $labels.name }}/{{ $labels.namespace }} has been only {{ $value | humanize }}% available over the last 10m on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes aggregated API is down.
              dashboard_url: default_dashboard_url
