additionalPrometheusRulesMap:
  kubelet-down:
    groups:
      - name: kubelet-down
        rules:
          - alert: kubelet-down-warning
            expr: absent(up{job="kubelet", metrics_path="/metrics"} == 1)
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubelet has disappeared from Prometheus target discovery.
              runbook_url: default_runbook_url
              summary: Target disappeared from Prometheus target discovery.
              dashboard_url: default_dashboard_url
          - alert: kubelet-down-critical
            expr: absent(up{job="kubelet", metrics_path="/metrics"} == 1)
            for: 15m
            labels:
              severity: critical
              group_name: kubelet-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubelet has disappeared from Prometheus target discovery.
              runbook_url: default_runbook_url
              summary: Target disappeared from Prometheus target discovery.
              dashboard_url: default_dashboard_url
