additionalPrometheusRulesMap:
  kube-client-certificate-expiration:
    groups:
      - name: kube-client-certificate-expiration
        rules:
          - alert: kube-client-certificate-expiration-warning
            expr: >-
              histogram_quantile(0.01, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400

              and on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-client-certificate-expiration
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: A client certificate used to authenticate to kubernetes apiserver is expiring in less than 24.0 hours on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Client certificate is about to expire.
              dashboard_url: default_dashboard_url
          - alert: kube-client-certificate-expiration-critical
            expr: >-
              histogram_quantile(0.01, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400

              and on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
            for: 15m
            labels:
              severity: critical
              group_name: kube-client-certificate-expiration
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: A client certificate used to authenticate to kubernetes apiserver is expiring in less than 24.0 hours on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Client certificate is about to expire.
              dashboard_url: default_dashboard_url
