additionalPrometheusRulesMap:
  kube-aggregated-api-errors:
    groups:
      - name: kube-aggregated-api-errors
        rules:
          - alert: kube-aggregated-api-errors-warning
            expr: sum by (cluster, instance, name, reason)(increase(aggregator_unavailable_apiservice_total{job="apiserver"}[1m])) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-aggregated-api-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes aggregated API {{ $labels.instance }}/{{ $labels.name }} has reported {{ $labels.reason }} errors on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes aggregated API has reported errors.
              dashboard_url: default_dashboard_url
          - alert: kube-aggregated-api-errors-critical
            expr: sum by (cluster, instance, name, reason)(increase(aggregator_unavailable_apiservice_total{job="apiserver"}[1m])) > 0
            for: 15m
            labels:
              severity: critical
              group_name: kube-aggregated-api-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes aggregated API {{ $labels.instance }}/{{ $labels.name }} has reported {{ $labels.reason }} errors on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes aggregated API has reported errors.
              dashboard_url: default_dashboard_url
