additionalPrometheusRulesMap:
  kube-api-error-budget-burn:
    groups:
      - name: kube-api-error-budget-burn
        rules:
          - alert: kube-api-error-budget-burn-warning
            expr: >-
              sum by (cluster) (apiserver_request:burnrate3d) > (1.00 * 0.01000)

              and on (cluster) sum by (cluster) (apiserver_request:burnrate6h) > (1.00 * 0.01000)
            for: 5m
            labels:
              severity: warning
              group_name: kube-api-error-budget-burn
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: The API server is burning too much error budget.
              dashboard_url: default_dashboard_url
          - alert: kube-api-error-budget-burn-critical
            expr: >-
              sum by (cluster) (apiserver_request:burnrate3d) > (1.00 * 0.01000)

              and on (cluster) sum by (cluster) (apiserver_request:burnrate6h) > (1.00 * 0.01000)
            for: 15m
            labels:
              severity: critical
              group_name: kube-api-error-budget-burn
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: The API server is burning too much error budget.
              dashboard_url: default_dashboard_url
