additionalPrometheusRulesMap:
  kube-node-unreachable:
    groups:
      - name: kube-node-unreachable
        rules:
          - alert: kube-node-unreachable-warning
            expr: >-
              (kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint{key=~"ToBeDeletedByClusterAutoscaler"}) == 1
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-unreachable
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                {{ $labels.node }} is unreachable and some workloads may be rescheduled on cluster.
                This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Node is unreachable.
              dashboard_url: default_dashboard_url
          - alert: kube-node-unreachable-critical
            expr: >-
              (kube_node_spec_taint{key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint{key=~"ToBeDeletedByClusterAutoscaler"}) == 1
            for: 10m
            labels:
              severity: critical
              group_name: kube-node-unreachable
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                {{ $labels.node }} is unreachable and some workloads may be rescheduled on cluster.
                This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Node is unreachable.
              dashboard_url: default_dashboard_url
