additionalPrometheusRulesMap:
  kube-node-not-ready:
    groups:
      - name: kube-node-not-ready
        rules:
          - alert: kube-node-not-ready-warning
            expr: >-
              kube_node_status_condition{condition="Ready", status="true"} == 0

              and on (node) kube_node_spec_unschedulable == 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-not-ready
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Node {{ $labels.node }} has been unready for more than 5 minutes.
              runbook_url: default_runbook_url
              summary: Node is not ready.
              dashboard_url: default_dashboard_url
          - alert: kube-node-not-ready-critical
            expr: >-
              kube_node_status_condition{condition="Ready", status="true"} == 0

              and on (node) kube_node_spec_unschedulable == 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-node-not-ready
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Node {{ $labels.node }} has been unready for more than 10 minutes.
              runbook_url: default_runbook_url
              summary: Node is not ready.
              dashboard_url: default_dashboard_url
