additionalPrometheusRulesMap:
  kubelet-pleg-duration-high:
    groups:
      - name: kubelet-pleg-duration-high
        rules:
          - alert: kubelet-pleg-duration-high-warning
            expr: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile{quantile="0.99"} >= 10
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-pleg-duration-high
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: The Kubelet Pod Lifecycle Event Generator has a 99th percentile duration of {{ $value }} seconds on node {{ $labels.node }} on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet Pod Lifecycle Event Generator is taking too long to relist.
              dashboard_url: default_dashboard_url
          - alert: kubelet-pleg-duration-high-critical
            expr: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile{quantile="0.99"} >= 10
            for: 15m
            labels:
              severity: critical
              group_name: kubelet-pleg-duration-high
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: The Kubelet Pod Lifecycle Event Generator has a 99th percentile duration of {{ $value }} seconds on node {{ $labels.node }} on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet Pod Lifecycle Event Generator is taking too long to relist.
              dashboard_url: default_dashboard_url
