additionalPrometheusRulesMap:
  kubelet-client-certificate-renewal-errors:
    groups:
      - name: kubelet-client-certificate-renewal-errors
        rules:
          - alert: kubelet-client-certificate-renewal-errors-warning
            expr: increase(kubelet_certificate_manager_client_expiration_renew_errors[5m]) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-client-certificate-renewal-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubelet on node {{ $labels.node }} has failed to renew its client certificate ({{ $value | humanize }} errors in the last 5 minutes) on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet has failed to renew its client certificate.
              dashboard_url: default_dashboard_url
          - alert: kubelet-client-certificate-renewal-errors-critical
            expr: increase(kubelet_certificate_manager_client_expiration_renew_errors[5m]) > 0
            for: 15m
            labels:
              severity: critical
              group_name: kubelet-client-certificate-renewal-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubelet on node {{ $labels.node }} has failed to renew its client certificate ({{ $value | humanize }} errors in the last 5 minutes) on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubelet has failed to renew its client certificate.
              dashboard_url: default_dashboard_url
