additionalPrometheusRulesMap:
  kube-version-mismatch:
    groups:
      - name: kube-version-mismatch
        rules:
          - alert: kube-version-mismatch-warning
            expr: >-
              count by (cluster) (count by (git_version, cluster) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"git_version","$1","git_version","(v[0-9]*.[0-9]*).*"))) > 1
            for: 5m
            labels:
              severity: warning
              group_name: kube-version-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: There are {{ $value }} different semantic versions of Kubernetes components running on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Different semantic versions of Kubernetes components running.
              dashboard_url: default_dashboard_url
          - alert: kube-version-mismatch-critical
            expr: >-
              count by (cluster) (count by (git_version, cluster) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"git_version","$1","git_version","(v[0-9]*.[0-9]*).*"))) > 1
            for: 15m
            labels:
              severity: critical
              group_name: kube-version-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: There are {{ $value }} different semantic versions of Kubernetes components running on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Different semantic versions of Kubernetes components running.
              dashboard_url: default_dashboard_url
