additionalPrometheusRulesMap:
  kubelet-pod-startup-latency-high:
    groups:
      - name: kubelet-pod-startup-latency-high
        rules:
          - alert: kubelet-pod-startup-latency-high-warning
            expr: >-
              histogram_quantile(0.99, sum by (instance, le) ( topk by (instance, le, operation_type) (1, rate(kubelet_pod_worker_duration_seconds_bucket{job="kubelet", metrics_path="/metrics"}[5m]) ) ) ) *

              on (instance) group_left(node) topk by (instance, node) (1, kubelet_node_name{job="kubelet", metrics_path="/metrics"} ) > 60
            for: 5m
            labels:
              severity: warning
              group_name: kubelet-pod-startup-latency-high
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Kubelet Pod startup 99th percentile latency is {{ $value }} seconds on node {{ $labels.node }}.
                This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Kubelet Pod startup latency is too high.
              dashboard_url: default_dashboard_url
          - alert: kubelet-pod-startup-latency-high-critical
            expr: >-
              histogram_quantile(0.99, sum by (instance, le) ( topk by (instance, le, operation_type) (1, rate(kubelet_pod_worker_duration_seconds_bucket{job="kubelet", metrics_path="/metrics"}[5m]) ) ) ) *

              on (instance) group_left(node) topk by (instance, node) (1, kubelet_node_name{job="kubelet", metrics_path="/metrics"} ) > 60
            for: 10m
            labels:
              severity: critical
              group_name: kubelet-pod-startup-latency-high
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Kubelet Pod startup 99th percentile latency is {{ $value }} seconds on node {{ $labels.node }}.
                This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Kubelet Pod startup latency is too high.
              dashboard_url: default_dashboard_url
