additionalPrometheusRulesMap:
  kube-node-eviction:
    groups:
      - name: kube-node-eviction
        rules:
          - alert: kube-node-eviction-warning
            expr: >-
              sum by (namespace, pod, node) (
                (kube_pod_status_reason{reason="Evicted"} == 1)
                * on (namespace, pod) group_left(node)
                kube_pod_info
              ) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-eviction
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
            annotations:
              description: >-
                Evictions have been detected on node {{ $labels.node }}. Investigate memory, disk, and ephemeral storage
                pressure along with recent evicted pods.
              runbook_url: default_runbook_url
              summary: Pod evictions detected on node {{ $labels.node }}
              dashboard_url: default_dashboard_url
          - alert: kube-node-eviction-critical
            expr: >-
              sum by (namespace, pod, node) (
                (kube_pod_status_reason{reason="Evicted"} == 1)
                * on (namespace, pod) group_left(node)
                kube_pod_info
              ) > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-node-eviction
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
            annotations:
              description: >-
                Evictions have been detected on node {{ $labels.node }}. Investigate memory, disk, and ephemeral storage
                pressure along with recent evicted pods.
              runbook_url: default_runbook_url
              summary: Pod evictions detected on node {{ $labels.node }}
              dashboard_url: default_dashboard_url
