additionalPrometheusRulesMap:
  kube-client-errors:
    groups:
      - name: kube-client-errors
        rules:
          - alert: kube-client-errors-warning
            expr: >-
              (sum(rate(rest_client_requests_total{job="apiserver",code=~"5.."}[5m])) by (cluster, instance, job, namespace) / sum(rate(rest_client_requests_total{job="apiserver"}[5m])) by (cluster, instance, job, namespace)) > 0.01
            for: 5m
            labels:
              severity: warning
              group_name: kube-client-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes API server client '{{ $labels.job }}/{{ $labels.instance }}' is experiencing {{ $value | humanizePercentage }} errors on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes API server client is experiencing errors.
              dashboard_url: default_dashboard_url
          - alert: kube-client-errors-critical
            expr: >-
              (sum(rate(rest_client_requests_total{job="apiserver",code=~"5.."}[5m])) by (cluster, instance, job, namespace) / sum(rate(rest_client_requests_total{job="apiserver"}[5m])) by (cluster, instance, job, namespace)) > 0.01
            for: 15m
            labels:
              severity: critical
              group_name: kube-client-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: Kubernetes API server client '{{ $labels.job }}/{{ $labels.instance }}' is experiencing {{ $value | humanizePercentage }} errors on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: Kubernetes API server client is experiencing errors.
              dashboard_url: default_dashboard_url
