additionalPrometheusRulesMap:
  kube-daemonset-not-scheduled:
    groups:
      - name: kube-daemonset-not-scheduled
        rules:
          - alert: kube-daemonset-not-scheduled-warning
            expr: >-
              kube_daemonset_status_number_misscheduled{namespace=~".*"} - kube_daemonset_status_current_number_scheduled{namespace=~".*"} > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-daemonset-not-scheduled
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: daemonset/{{ $labels.namespace }}/{{ $labels.daemonset }}
              correlation_scope: daemonset
            annotations:
              description: >-
                {{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled
                on cluster {{ $labels.cluster }}. This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: DaemonSet pods are not scheduled.
              dashboard_url: default_dashboard_url
          - alert: kube-daemonset-not-scheduled-critical
            expr: >-
              kube_daemonset_status_number_misscheduled{namespace=~".*"} - kube_daemonset_status_current_number_scheduled{namespace=~".*"} > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-daemonset-not-scheduled
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: daemonset/{{ $labels.namespace }}/{{ $labels.daemonset }}
              correlation_scope: daemonset
            annotations:
              description: >-
                {{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled
                on cluster {{ $labels.cluster }}. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: DaemonSet pods are not scheduled.
              dashboard_url: default_dashboard_url
