additionalPrometheusRulesMap:
  kube-node-not-ready:
    groups:
      - name: kube-node-not-ready
        rules:
          # NOTE: k8s.node.condition is an optional metric that needs enabling with node.condition_type_to_report
          # kube_node_spec_unschedulable may not be available in OTel k8sclusterreceiver
          - alert: kube-node-not-ready-warning
            expr: >-
              k8s.node.condition{job="otelcol-k8scluster",condition="Ready",status="true"} == 0

              and on (cluster, node) kube_node_spec_unschedulable{job="kube-state-metrics"} == 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-not-ready
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: "{{ $labels.node }} has been unready for more than 5 minutes on cluster {{ $labels.cluster }}."
              runbook_url: default_runbook_url
              summary: Node is not ready.
              dashboard_url: default_dashboard_url
          # NOTE: k8s.node.condition is an optional metric that needs enabling with node.condition_type_to_report
          # kube_node_spec_unschedulable may not be available in OTel k8sclusterreceiver
          - alert: kube-node-not-ready-critical
            expr: >-
              k8s.node.condition{job="otelcol-k8scluster",condition="Ready",status="true"} == 0

              and on (cluster, node) kube_node_spec_unschedulable{job="kube-state-metrics"} == 0
            for: 15m
            labels:
              severity: critical
              group_name: kube-node-not-ready
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: "{{ $labels.node }} has been unready for more than 15 minutes on cluster {{ $labels.cluster }}."
              runbook_url: default_runbook_url
              summary: Node is not ready.
              dashboard_url: default_dashboard_url
