additionalPrometheusRulesMap:
  kube-api-down:
    groups:
      - name: kube-api-down
        rules:
          - alert: kube-api-down-warning
            expr: absent(up{job="apiserver"} == 1)
            for: 5m
            labels:
              severity: warning
              group_name: kube-api-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: KubeAPI has disappeared from Prometheus target discovery.
              runbook_url: default_runbook_url
              summary: Target disappeared from Prometheus target discovery.
              dashboard_url: default_dashboard_url
          - alert: kube-api-down-critical
            expr: absent(up{job="apiserver"} == 1)
            for: 15m
            labels:
              severity: critical
              group_name: kube-api-down
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: KubeAPI has disappeared from Prometheus target discovery.
              runbook_url: default_runbook_url
              summary: Target disappeared from Prometheus target discovery.
              dashboard_url: default_dashboard_url
