additionalPrometheusRulesMap:
  kube-daemonset-rollout-stuck:
    groups:
      - name: kube-daemonset-rollout-stuck
        rules:
          - alert: kube-daemonset-rollout-stuck-warning
            expr: >-
              ( ( kube_daemonset_status_current_number_scheduled{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} )

              or ( kube_daemonset_status_number_misscheduled{namespace=~".*"} != 0 )

              or ( kube_daemonset_status_updated_number_scheduled{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} )

              or ( kube_daemonset_status_number_available{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} ) )

              and ( changes(kube_daemonset_status_updated_number_scheduled{namespace=~".*"}[5m]) == 0 )
            for: 5m
            labels:
              severity: warning
              group_name: kube-daemonset-rollout-stuck
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: daemonset/{{ $labels.namespace }}/{{ $labels.daemonset }}
              correlation_scope: daemonset
            annotations:
              description: >-
                DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at
                least 5 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: DaemonSet rollout is stuck.
              dashboard_url: default_dashboard_url
          - alert: kube-daemonset-rollout-stuck-critical
            expr: >-
              ( ( kube_daemonset_status_current_number_scheduled{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} )

              or ( kube_daemonset_status_number_misscheduled{namespace=~".*"} != 0 )

              or ( kube_daemonset_status_updated_number_scheduled{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} )

              or ( kube_daemonset_status_number_available{namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{namespace=~".*"} ) )

              and ( changes(kube_daemonset_status_updated_number_scheduled{namespace=~".*"}[5m]) == 0 )
            for: 10m
            labels:
              severity: critical
              group_name: kube-daemonset-rollout-stuck
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
              correlation_key: daemonset/{{ $labels.namespace }}/{{ $labels.daemonset }}
              correlation_scope: daemonset
            annotations:
              description: >-
                DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at
                least 10 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: DaemonSet rollout is stuck.
              dashboard_url: default_dashboard_url
