additionalPrometheusRulesMap:
  kube-node-pressure:
    groups:
      - name: kube-node-pressure
        rules:
          - alert: kube-node-pressure-warning
            expr: >-
              kube_node_status_condition{condition=~"(MemoryPressure|DiskPressure|PIDPressure)",status="true"} == 1

              and on (node) kube_node_spec_unschedulable == 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-node-pressure
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Node {{ $labels.node }} has active Condition {{ $labels.condition }}.
                This is caused by resource usage exceeding eviction thresholds. This warning alert fires
                after 5m.
              runbook_url: default_runbook_url
              summary: Node has as active Condition.
              dashboard_url: default_dashboard_url
          - alert: kube-node-pressure-critical
            expr: >-
              kube_node_status_condition{condition=~"(MemoryPressure|DiskPressure|PIDPressure)",status="true"} == 1

              and on (node) kube_node_spec_unschedulable == 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-node-pressure
              node_hostname: '{{ $labels.node }}'
              affected_node: '{{ $labels.node }}'
              correlation_key: node/{{ $labels.node }}
              correlation_scope: node
              root_cause: 'true'
            annotations:
              description: >-
                Node {{ $labels.node }} has active Condition {{ $labels.condition }}.
                This is caused by resource usage exceeding eviction thresholds. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Node has as active Condition.
              dashboard_url: default_dashboard_url
