groups:
- name: prometheus
  rules:
  - alert: PrometheusTSDBReloadsFailing
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has detected {{$value
        | humanize}} reload failures over the last 3h.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheustsdbreloadsfailing
      summary: Prometheus has issues reloading blocks from disk.
    expr: increase(prometheus_tsdb_reloads_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[3h])
      > 0
    for: 4h
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
