groups:
- name: prometheus
  rules:
  - alert: PrometheusRuleFailures
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to
        evaluate {{ printf "%.0f" $value }} rules in the last 5m.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusrulefailures
      summary: Prometheus is failing rule evaluations.
    expr: increase(prometheus_rule_evaluation_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m])
      > 0
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: critical
