groups:
- name: prometheus
  rules:
  - alert: PrometheusScrapeBodySizeLimitHit
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed {{
        printf "%.0f" $value }} scrapes in the last 5m because some targets exceeded
        the configured body_size_limit.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusscrapebodysizelimithit
      summary: Prometheus has dropped some targets that exceeded body size limit.
    expr: increase(prometheus_target_scrapes_exceeded_body_size_limit_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m])
      > 0
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
