groups:
- name: prometheus
  rules:
  - alert: PrometheusRemoteWriteDesiredShards
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} remote write desired
        shards calculation wants to run {{ $value }} shards for queue {{ $labels.remote_name}}:{{
        $labels.url }}, which is more than the max of {{ printf `prometheus_remote_storage_shards_max{instance="%s",job="kube-prometheus-stack-prometheus",namespace="prometheus"}`
        $labels.instance | query | first | value }}.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusremotewritedesiredshards
      summary: Prometheus remote write desired shards calculation wants to run more
        than configured max shards.
    expr: "# Without max_over_time, failed scrapes could create false negatives, see\n\
      # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.\n\
      (\n  max_over_time(prometheus_remote_storage_shards_desired{job=\"kube-prometheus-stack-prometheus\"\
      ,namespace=\"prometheus\"}[5m])\n>\n  max_over_time(prometheus_remote_storage_shards_max{job=\"\
      kube-prometheus-stack-prometheus\",namespace=\"prometheus\"}[5m])\n)"
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
