groups:
- name: prometheus
  rules:
  - alert: PrometheusOutOfOrderTimestamps
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{
        printf "%.4g" $value  }} samples/s with timestamps arriving out of order.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusoutofordertimestamps
      summary: Prometheus drops samples with out-of-order timestamps.
    expr: rate(prometheus_target_scrapes_sample_out_of_order_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m])
      > 0
    for: 10m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
