groups:
- name: prometheus
  rules:
  - alert: PrometheusNotIngestingSamples
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting
        samples.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusnotingestingsamples
      summary: Prometheus is not ingesting samples.
    expr: "(\n  sum without(type) (rate(prometheus_tsdb_head_samples_appended_total{job=\"\
      kube-prometheus-stack-prometheus\",namespace=\"prometheus\"}[5m])) <= 0\nand\n\
      \  (\n    sum without(scrape_job) (prometheus_target_metadata_cache_entries{job=\"\
      kube-prometheus-stack-prometheus\",namespace=\"prometheus\"}) > 0\n  or\n  \
      \  sum without(rule_group) (prometheus_rule_group_rules{job=\"kube-prometheus-stack-prometheus\"\
      ,namespace=\"prometheus\"}) > 0\n  )\n)"
    for: 10m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
