groups:
- name: prometheus
  rules:
  - alert: PrometheusSDRefreshFailure
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to
        refresh SD with mechanism {{$labels.mechanism}}.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheussdrefreshfailure
      summary: Failed Prometheus SD refresh.
    expr: increase(prometheus_sd_refresh_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[10m])
      > 0
    for: 20m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
