groups:
- name: prometheus
  rules:
  - alert: PrometheusKubernetesListWatchFailures
    annotations:
      description: Kubernetes service discovery of Prometheus {{$labels.namespace}}/{{$labels.pod}}
        is experiencing {{ printf "%.0f" $value }} failures with LIST/WATCH requests
        to the Kubernetes API in the last 5 minutes.
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheuskuberneteslistwatchfailures
      summary: Requests in Kubernetes SD are failing.
    expr: increase(prometheus_sd_kubernetes_failures_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m])
      > 0
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
