groups:
- name: prometheus
  rules:
  - alert: PrometheusErrorSendingAlertsToSomeAlertmanagers
    annotations:
      description: '{{ printf "%.1f" $value }}% of alerts sent by Prometheus {{$labels.namespace}}/{{$labels.pod}}
        to Alertmanager {{$labels.alertmanager}} were affected by errors.'
      runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheuserrorsendingalertstosomealertmanagers
      summary: More than 1% of alerts sent by Prometheus to a specific Alertmanager
        were affected by errors.
    expr: "(\n  rate(prometheus_notifications_errors_total{job=\"kube-prometheus-stack-prometheus\"\
      ,namespace=\"prometheus\"}[5m])\n/\n  rate(prometheus_notifications_sent_total{job=\"\
      kube-prometheus-stack-prometheus\",namespace=\"prometheus\"}[5m])\n)\n* 100\n\
      > 1"
    for: 15m
    labels:
      rackspace_com_coreAccountID: '5002029'
      rackspace_com_overseerID: '935811'
      severity: warning
